name: SuperQ - smokeping_prober
version: 0.1.4
slug: smokeping_prober
image: aaroncarson/hass_smokeping_prober
description: Prometheus style smokeping
arch:
  - i386
  - amd64
  - armhf
  - aarch64
startup: application
boot: auto
host_network: true
options:
  targets:
    - hosts:
        - "google.com" 
        - "1.1.1.1"
        - "8.8.8.8"
        - "213.106.255.109"
      interval: "1s"
      network: "ip"
      protocol: "icmp"
      size: 56
schema:
  targets:
    - hosts:
        - str
      interval: str
      network: str
      protocol: str
      size: int
