name: Scrypted
version: 0.0.1
slug: scrypted
description: Scrypted is a home automation platform primarily focusing on making camera experiences seamless.
arch:
  - amd64
  - armhf
  - aarch64
startup: application
boot: auto
ingress: true
ingress_port: 10443
ingress_stream: true
panel_icon: mdi:camera
