name: Docker build - InfluxDB2
on:
  push:
    branches:
      - main
    paths:
      - influxdb2/**
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get build metadata
        id: build_metadata
        uses: pietrobolcato/action-read-yaml@1.1.0
        with:
          config: {{ github.workspace}}/influxdb2/influxdb2/config.yaml

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./influxdb2
          platforms: linux/amd64 #,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            BUILD_DATE=${{ steps.date.output.date }}
            BUILD_DESCRIPTION=${{ steps.build_metadata.outputs['description'] }}
            BUILD_NAME=${{ steps.build_metadata.outputs['name'] }}
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.server_url }}/${{ github.repository }}
            BUILD_VERSION=${{ steps.build_metadata.outputs['version'] }}
          tags: |
            aaroncarson/ha-addon-influxdb2:latest
            aaroncarson/ha-addon-influxdb2:${{ steps.build_metadata.outputs['version'] }}
            aaroncarson/ha-addon-influxdb2:${{ github.sha }}